# Generated by Django 5.0 on 2025-02-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='alocacao',
            field=models.CharField(choices=[('VEICULO', 'Veículo'), ('FRETE', 'Frete'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20),
        ),
    ]
