# Generated by Django 5.0 on 2025-02-26 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='Renavam')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('vida_util', models.IntegerField(verbose_name='Vida Útil (anos)')),
                ('valor_residual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Residual')),
                ('capacidade_carga', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidade de Carga (kg)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('VENDIDO', 'Vendido'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('quilometragem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quilometragem Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Caminhão',
                'verbose_name_plural': 'Caminhões',
                'ordering': ['placa'],
            },
        ),
    ]
