# Generated by Django 5.0 on 2025-02-26 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carreta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_configuracao', models.DateField(verbose_name='Data de Configuração')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caminhao', verbose_name='Caminhão')),
                ('carreta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjunto_carreta1', to='core.carreta', verbose_name='Carreta 1')),
                ('carreta2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjunto_carreta2', to='core.carreta', verbose_name='Carreta 2')),
                ('carreta3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjunto_carreta3', to='core.carreta', verbose_name='Carreta 3')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjuntos',
                'ordering': ['-data_configuracao'],
            },
        ),
    ]
