# Generated by Django 5.0 on 2025-02-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(verbose_name='Data de Saída')),
                ('data_chegada', models.DateField(blank=True, null=True, verbose_name='Data de Chegada')),
                ('peso_carga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso da Carga (kg)')),
                ('km_saida', models.IntegerField(verbose_name='Km de Saída')),
                ('km_chegada', models.IntegerField(blank=True, null=True, verbose_name='Km de Chegada')),
                ('conta_bancaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conta Bancária')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('origem', models.CharField(max_length=100, verbose_name='Origem')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('nota_fiscal', models.CharField(max_length=50, verbose_name='Nota Fiscal')),
                ('ticket', models.CharField(max_length=50, verbose_name='Ticket')),
                ('comissao_motorista', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão do Motorista (%)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Acréscimo')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Desconto')),
                ('status', models.CharField(default='PENDENTE', max_length=20, verbose_name='Status')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.caminhao', verbose_name='Caminhão')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carga', verbose_name='Tipo de Carga')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='fretes_como_cliente', to='core.contato', verbose_name='Cliente')),
                ('motorista', models.ForeignKey(limit_choices_to={'tipo': 'MOTORISTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='fretes_como_motorista', to='core.contato', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Fretes',
                'ordering': ['-data_saida'],
            },
        ),
    ]
