# Generated by Django 5.0 on 2025-02-27 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_valor_comissao_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Abastecimento')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('situacao', models.CharField(choices=[('EM_PERCURSO', 'Em Percurso'), ('FINAL_FRETE', 'Final de Frete')], max_length=20, verbose_name='Situação')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros')),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R$/Litro')),
                ('km_abastecimento', models.IntegerField(verbose_name='KM do Abastecimento')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.caminhao', verbose_name='Caminhão')),
                ('frete_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.frete', verbose_name='Frete Atual')),
                ('motorista', models.ForeignKey(limit_choices_to={'tipo': 'MOTORISTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos_motorista', to='core.contato', verbose_name='Motorista')),
                ('posto', models.ForeignKey(limit_choices_to={'tipo': 'POSTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos_posto', to='core.contato', verbose_name='Posto')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data'],
            },
        ),
    ]
