# Generated by Django 5.0 on 2025-02-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_total_valor_abastecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='frete_atual',
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='total_valor',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.CreateModel(
            name='EstimativaPneus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('preco_pneu_direcional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Pneu Direcional')),
                ('preco_pneu_tracao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Pneu de Tração')),
                ('preco_pneu_cargo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Pneu de Carga')),
                ('vida_util_direcional_km', models.IntegerField(verbose_name='Vida Útil do Pneu Direcional (km)')),
                ('vida_util_tracao_km', models.IntegerField(verbose_name='Vida Útil do Pneu de Tração (km)')),
                ('vida_util_cargo_km', models.IntegerField(verbose_name='Vida Útil do Pneu de Carga (km)')),
                ('numero_recapagens_direcional', models.IntegerField(verbose_name='Número de Recapagens - Direcional')),
                ('numero_recapagens_tracao', models.IntegerField(verbose_name='Número de Recapagens - Tração')),
                ('numero_recapagens_cargo', models.IntegerField(verbose_name='Número de Recapagens - Carga')),
                ('custo_recapagem_direcional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo da Recapagem - Direcional')),
                ('custo_recapagem_tracao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo da Recapagem - Tração')),
                ('custo_recapagem_cargo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo da Recapagem - Carga')),
                ('custo_total_por_km', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Custo Total por KM')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conjunto', verbose_name='Conjunto')),
            ],
            options={
                'verbose_name': 'Estimativa de Pneus',
                'verbose_name_plural': 'Estimativas de Pneus',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
