# Generated by Django 5.0 on 2025-02-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recreate_estimativa_pneus'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimativapneus',
            name='custo_total_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
