# Generated by Django 5.0 on 2025-02-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_estimativamanutencao_itemmanutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimativamanutencao',
            name='custo_total_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
