# Generated by Django 5.0 on 2025-02-27 05:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_estimativamanutencao_custo_total_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimativaCustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_estimativa', models.DateField(default=django.utils.timezone.now)),
                ('custo_total_dia', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conjunto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ANUAL', 'Anual'), ('MENSAL', 'Mensal')], default='ANUAL', max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_por_dia', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('estimativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.estimativacustofixo')),
            ],
        ),
    ]
