# Generated by Django 5.0 on 2025-02-27 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_estimativacustofixo_itemcustofixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('caminhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.caminhao')),
                ('carreta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.carreta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contato')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('frete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.frete')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subcategoria')),
            ],
        ),
    ]
