# Generated by Django 5.0 on 2025-02-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='chassi',
            field=models.CharField(max_length=17, verbose_name='Chassi'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='placa',
            field=models.CharField(max_length=8, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='renavam',
            field=models.CharField(max_length=11, verbose_name='Renavam'),
        ),
    ]
