# Generated by Django 5.0 on 2025-02-28 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_caminhao_chassi_alter_caminhao_placa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('MOTORISTA', 'Motorista'), ('FUNCIONARIO', 'Funcionário'), ('POSTO', 'Posto de Combustível')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='AbastecimentoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('combustivel', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL_S10', 'Diesel S10'), ('ARLA_32', 'Arla 32')], max_length=20, verbose_name='Combustível')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros')),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Litro')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('km_atual', models.IntegerField(verbose_name='Quilometragem Atual')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caminhao')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos_pendentes', to=settings.AUTH_USER_MODEL)),
                ('posto', models.ForeignKey(limit_choices_to={'tipo': 'POSTO'}, on_delete=django.db.models.deletion.CASCADE, to='core.contato')),
            ],
            options={
                'verbose_name': 'Abastecimento Pendente',
                'verbose_name_plural': 'Abastecimentos Pendentes',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('MOTORISTA', 'Motorista'), ('USUARIO', 'Usuário Regular')], default='USUARIO', max_length=20, verbose_name='Tipo de Usuário')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH')),
                ('categoria_cnh', models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoria CNH')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('receber_notificacoes', models.BooleanField(default=True, verbose_name='Receber Notificações')),
                ('token_notificacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Notificação')),
                ('caminhao_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_atual', to='core.caminhao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
