# Generated by Django 5.0 on 2025-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contato_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('FUNCIONARIO', 'Funcionário'), ('POSTO', 'Posto de Combustível')], max_length=20, verbose_name='Tipo'),
        ),
    ]
