# Generated by Django 5.0 on 2025-03-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_perfilusuario_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='motorista_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fretes_como_motorista_user', to=settings.AUTH_USER_MODEL, verbose_name='Motorista (Usuário)'),
        ),
    ]
