# Generated by Django 5.0 on 2025-03-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_frete_motorista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frete',
            name='motorista',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MOTORISTA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fretes_como_motorista', to='core.contato', verbose_name='Motorista'),
        ),
    ]
