# Generated by Django 5.0 on 2025-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_abastecimento_frete_abastecimento_tipo_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='tipo_combustivel',
            field=models.CharField(blank=True, choices=[('DIESEL_S10', 'Diesel S10'), ('DIESEL_S500', 'Diesel S500')], default='DIESEL_S10', max_length=20, null=True, verbose_name='Tipo de Combustível'),
        ),
    ]
