# Generated by Django 5.0 on 2025-04-03 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_abastecimento_tipo_combustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentopendente',
            name='frete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.frete', verbose_name='Frete Associado'),
        ),
        migrations.AlterField(
            model_name='abastecimentopendente',
            name='combustivel',
            field=models.CharField(choices=[('DIESEL_S10', 'Diesel S10'), ('DIESEL_S500', 'Diesel S500')], max_length=20, verbose_name='Combustível'),
        ),
    ]
