# Generated by Django 5.0 on 2025-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_abastecimentopendente_frete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentopendente',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='abastecimentopendente',
            name='situacao',
            field=models.CharField(blank=True, choices=[('EM_PERCURSO', 'Em Percurso'), ('FINAL_FRETE', 'Final de Frete')], default='EM_PERCURSO', max_length=20, null=True, verbose_name='Situação'),
        ),
    ]
