# Generated by Django 5.0 on 2025-04-04 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_abastecimentopendente_data_vencimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='motorista_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos_motorista_user', to=settings.AUTH_USER_MODEL, verbose_name='Motorista (Usuário)'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MOTORISTA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos_motorista', to='core.contato', verbose_name='Motorista'),
        ),
    ]
