# Generated by Django 5.0 on 2025-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_abastecimento_motorista_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentopendente',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
