# Generated by Django 5.0 on 2025-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_abastecimentopendente_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='origem_pendente',
            field=models.BooleanField(default=False, help_text='Indica se o abastecimento foi criado a partir de um abastecimento pendente', verbose_name='Origem Pendente'),
        ),
    ]
