# Generated by Django 5.0 on 2025-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_abastecimento_abastecimento_pendente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='status_andamento',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status de Andamento'),
        ),
    ]
