# Generated by Django 5.0 on 2025-04-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_frete_status_andamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='asaas_cobranca_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Cobrança (Asaas)'),
        ),
        migrations.AddField(
            model_name='frete',
            name='asaas_data_criacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação da Cobrança'),
        ),
        migrations.AddField(
            model_name='frete',
            name='asaas_data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento da Cobrança'),
        ),
        migrations.AddField(
            model_name='frete',
            name='asaas_link_pagamento',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Pagamento'),
        ),
        migrations.AddField(
            model_name='frete',
            name='asaas_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebida'), ('CONFIRMED', 'Confirmada'), ('OVERDUE', 'Vencida'), ('REFUNDED', 'Estornada'), ('CANCELED', 'Cancelada'), ('NAO_GERADA', 'Não Gerada')], default='NAO_GERADA', max_length=50, verbose_name='Status da Cobrança'),
        ),
        migrations.AddField(
            model_name='frete',
            name='asaas_valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total da Cobrança'),
        ),
        migrations.CreateModel(
            name='AsaasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='Chave de API Asaas')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='Ambiente de Testes')),
                ('taxa_sistema', models.DecimalField(decimal_places=2, default=9.99, max_digits=10, verbose_name='Taxa do Sistema (R$)')),
                ('asaas_account_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da Conta Asaas')),
                ('wallet_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet ID (Split)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração Asaas',
                'verbose_name_plural': 'Configurações Asaas',
            },
        ),
    ]
