# Generated by Django 5.0 on 2025-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_frete_asaas_cobranca_id_frete_asaas_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asaasconfig',
            options={'verbose_name': 'Configuração de Cobranças', 'verbose_name_plural': 'Configurações de Cobranças'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='company_type',
            field=models.CharField(choices=[('MEI', 'Microempreendedor Individual (MEI)'), ('EIRELI', 'Empresa Individual de Responsabilidade Limitada (EIRELI)'), ('LTDA', 'Sociedade Limitada (LTDA)'), ('SA', 'Sociedade Anônima (S.A.)'), ('INSTITUITION_NGO_ASSOCIATION', 'Instituição/ONG/Associação')], default='LTDA', max_length=30, verbose_name='Tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='asaasconfig',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='Chave de API do Sistema de Cobranças'),
        ),
        migrations.AlterField(
            model_name='frete',
            name='asaas_cobranca_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Cobrança'),
        ),
    ]
