# Generated by Django 5.0 on 2025-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_asaasconfig_options_empresa_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='company_type',
            field=models.CharField(choices=[('MEI', 'Microempreendedor Individual (MEI)'), ('LIMITED', 'Sociedade Limitada (LTDA)'), ('INDIVIDUAL', 'Empresa Individual'), ('ASSOCIATION', 'Associação/ONG')], default='LIMITED', max_length=30, verbose_name='Tipo de Empresa'),
        ),
    ]
