# Generated by Django 5.0 on 2025-04-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_empresa_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asaasconfig',
            name='api_key',
            field=models.CharField(max_length=512, verbose_name='Chave de API do Sistema de Cobranças (criptografada)'),
        ),
    ]
