# Generated by Django 5.0 on 2025-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_asaasconfig_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
    ]
