# Generated by Django 5.0 on 2025-04-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_frete_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frete',
            name='conta_bancaria',
        ),
        migrations.AddField(
            model_name='asaasconfig',
            name='obrigar_cobranca',
            field=models.BooleanField(default=False, help_text='Se marcado, o usuário será obrigado a gerar cobrança ao cadastrar fretes', verbose_name='Obrigar geração de cobrança'),
        ),
    ]
