# Generated by Django 5.0 on 2025-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_frete_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Obrigatório para clientes', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, help_text='Obrigatório para clientes', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, help_text='Obrigatório para clientes', max_length=15, verbose_name='Telefone'),
        ),
    ]
